apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellowhale
  labels:
    app: hellowhale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellowhale
  template: 
    metadata: 
      labels: 
        app: hellowhale 
    spec:
      containers:
        - name: hellowhale
          image: kartikrj/hellowhale
          ports:
            - containerPort: 80
      imagePullSecrets:
      - name: docker-creds

---
apiVersion: v1
kind: Service
metadata:
  name: hellowhale
spec:
  type: LoadBalancer
  selector:
    app: hellowhale
  ports:
    - port: 80
      
