apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellowhale
  labels:
    app: hellowhale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellowhale
  template: 
    metadata: 
      labels: 
        app: hellowhale 
    spec:
      containers:
        - name: hellowhale
          image: kartikrj/hellowhale
          ports:
            - containerPort: 8080
      imagePullSecrets:
      - name: acs-plugin--10lqccqmr1
